package com.yonyou.itf.mdm07.sharing;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-07T00:36:29.533+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "IMdSharingCenterService", 
                  wsdlLocation = "http://192.168.102.84:8089/uapws/service/com.yonyou.itf.mdm07.sharing.IMdSharingCenterService?wsdl",
                  targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService") 
public class IMdSharingCenterService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", "IMdSharingCenterService");
    public final static QName IMdSharingCenterServiceSOAP11PortHttp = new QName("http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", "IMdSharingCenterServiceSOAP11port_http");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.102.84:8089/uapws/service/com.yonyou.itf.mdm07.sharing.IMdSharingCenterService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IMdSharingCenterService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.102.84:8089/uapws/service/com.yonyou.itf.mdm07.sharing.IMdSharingCenterService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IMdSharingCenterService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IMdSharingCenterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMdSharingCenterService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IMdSharingCenterService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IMdSharingCenterService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IMdSharingCenterService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IMdSharingCenterServicePortType
     */
    @WebEndpoint(name = "IMdSharingCenterServiceSOAP11port_http")
    public IMdSharingCenterServicePortType getIMdSharingCenterServiceSOAP11PortHttp() {
        return super.getPort(IMdSharingCenterServiceSOAP11PortHttp, IMdSharingCenterServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMdSharingCenterServicePortType
     */
    @WebEndpoint(name = "IMdSharingCenterServiceSOAP11port_http")
    public IMdSharingCenterServicePortType getIMdSharingCenterServiceSOAP11PortHttp(WebServiceFeature... features) {
        return super.getPort(IMdSharingCenterServiceSOAP11PortHttp, IMdSharingCenterServicePortType.class, features);
    }

}
