package com.yonyou.itf.mdm07.sharing;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-07T00:36:29.512+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", name = "IMdSharingCenterServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IMdSharingCenterServicePortType {

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:queryMdById", output = "urn:queryMdByIdResponse")
    @RequestWrapper(localName = "queryMdById", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryMdById")
    @WebMethod(action = "urn:queryMdById")
    @ResponseWrapper(localName = "queryMdByIdResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryMdByIdResponse")
    public com.yonyou.itf.mdm07.sharing.MdmRetVO queryMdById(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "string2", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string2,
        @WebParam(name = "boolean", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.Boolean _boolean
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:insertMd", output = "urn:insertMdResponse")
    @RequestWrapper(localName = "insertMd", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.InsertMd")
    @WebMethod(action = "urn:insertMd")
    @ResponseWrapper(localName = "insertMdResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.InsertMdResponse")
    public com.yonyou.itf.mdm07.sharing.MdmRetVO insertMd(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "string2", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string2
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:deleteMdById", output = "urn:deleteMdByIdResponse")
    @RequestWrapper(localName = "deleteMdById", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.DeleteMdById")
    @WebMethod(action = "urn:deleteMdById")
    @ResponseWrapper(localName = "deleteMdByIdResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.DeleteMdByIdResponse")
    public com.yonyou.itf.mdm07.sharing.MdmRetVO deleteMdById(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "string2", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string2
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:subscribeMd", output = "urn:subscribeMdResponse")
    @RequestWrapper(localName = "subscribeMd", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.SubscribeMd")
    @WebMethod(action = "urn:subscribeMd")
    @ResponseWrapper(localName = "subscribeMdResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.SubscribeMdResponse")
    public java.lang.String subscribeMd(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "boolean", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.Boolean _boolean
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:queryMdByCode", output = "urn:queryMdByCodeResponse")
    @RequestWrapper(localName = "queryMdByCode", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryMdByCode")
    @WebMethod(action = "urn:queryMdByCode")
    @ResponseWrapper(localName = "queryMdByCodeResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryMdByCodeResponse")
    public com.yonyou.itf.mdm07.sharing.MdmRetVO queryMdByCode(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "string2", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string2,
        @WebParam(name = "boolean", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.Boolean _boolean
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:queryXmlMdById", output = "urn:queryXmlMdByIdResponse")
    @RequestWrapper(localName = "queryXmlMdById", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryXmlMdById")
    @WebMethod(action = "urn:queryXmlMdById")
    @ResponseWrapper(localName = "queryXmlMdByIdResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryXmlMdByIdResponse")
    public com.yonyou.itf.mdm07.sharing.MdmRetVO queryXmlMdById(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "string2", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string2,
        @WebParam(name = "boolean", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.Boolean _boolean
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:queryMdByCondition", output = "urn:queryMdByConditionResponse")
    @RequestWrapper(localName = "queryMdByCondition", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryMdByCondition")
    @WebMethod(action = "urn:queryMdByCondition")
    @ResponseWrapper(localName = "queryMdByConditionResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryMdByConditionResponse")
    public com.yonyou.itf.mdm07.sharing.MdmRetVO queryMdByCondition(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "string2", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string2,
        @WebParam(name = "boolean", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.Boolean _boolean,
        @WebParam(name = "string4", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string4
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:updateMd", output = "urn:updateMdResponse")
    @RequestWrapper(localName = "updateMd", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.UpdateMd")
    @WebMethod(action = "urn:updateMd")
    @ResponseWrapper(localName = "updateMdResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.UpdateMdResponse")
    public com.yonyou.itf.mdm07.sharing.MdmRetVO updateMd(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "string2", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string2
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:queryXmlListMdByType", output = "urn:queryXmlListMdByTypeResponse")
    @RequestWrapper(localName = "queryXmlListMdByType", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryXmlListMdByType")
    @WebMethod(action = "urn:queryXmlListMdByType")
    @ResponseWrapper(localName = "queryXmlListMdByTypeResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryXmlListMdByTypeResponse")
    public com.yonyou.itf.mdm07.sharing.MdmRetVO queryXmlListMdByType(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "boolean", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.Boolean _boolean
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:queryIdsSingle", output = "urn:queryIdsSingleResponse")
    @RequestWrapper(localName = "queryIdsSingle", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryIdsSingle")
    @WebMethod(action = "urn:queryIdsSingle")
    @ResponseWrapper(localName = "queryIdsSingleResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryIdsSingleResponse")
    public java.util.List<com.yonyou.itf.mdm07.sharing.QueryIdsSingleResponse.Return> queryIdsSingle(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "list", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.util.List<java.lang.String> list,
        @WebParam(name = "string3", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string3
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:changeBackgroundTaskStatus", output = "urn:changeBackgroundTaskStatusResponse")
    @RequestWrapper(localName = "changeBackgroundTaskStatus", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.ChangeBackgroundTaskStatus")
    @WebMethod(action = "urn:changeBackgroundTaskStatus")
    @ResponseWrapper(localName = "changeBackgroundTaskStatusResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.ChangeBackgroundTaskStatusResponse")
    public java.lang.String changeBackgroundTaskStatus(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "boolean", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.Boolean _boolean
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:queryMdByName", output = "urn:queryMdByNameResponse")
    @RequestWrapper(localName = "queryMdByName", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryMdByName")
    @WebMethod(action = "urn:queryMdByName")
    @ResponseWrapper(localName = "queryMdByNameResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryMdByNameResponse")
    public com.yonyou.itf.mdm07.sharing.MdmRetVO queryMdByName(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "string2", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string2,
        @WebParam(name = "boolean", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.Boolean _boolean
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:queryListMdByType", output = "urn:queryListMdByTypeResponse")
    @RequestWrapper(localName = "queryListMdByType", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryListMdByType")
    @WebMethod(action = "urn:queryListMdByType")
    @ResponseWrapper(localName = "queryListMdByTypeResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryListMdByTypeResponse")
    public com.yonyou.itf.mdm07.sharing.MdmRetVO queryListMdByType(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "boolean", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.Boolean _boolean
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:queryNewMdAfter", output = "urn:queryNewMdAfterResponse")
    @RequestWrapper(localName = "queryNewMdAfter", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryNewMdAfter")
    @WebMethod(action = "urn:queryNewMdAfter")
    @ResponseWrapper(localName = "queryNewMdAfterResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryNewMdAfterResponse")
    public com.yonyou.itf.mdm07.sharing.MdmRetVO queryNewMdAfter(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "string2", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string2,
        @WebParam(name = "boolean", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.Boolean _boolean
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:queryListMdByIds", output = "urn:queryListMdByIdsResponse")
    @RequestWrapper(localName = "queryListMdByIds", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryListMdByIds")
    @WebMethod(action = "urn:queryListMdByIds")
    @ResponseWrapper(localName = "queryListMdByIdsResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryListMdByIdsResponse")
    public com.yonyou.itf.mdm07.sharing.MdmRetVO queryListMdByIds(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "list", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.util.List<java.lang.String> list,
        @WebParam(name = "boolean", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.Boolean _boolean
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:queryMDMCodeByIdsMulti", output = "urn:queryMDMCodeByIdsMultiResponse")
    @RequestWrapper(localName = "queryMDMCodeByIdsMulti", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryMDMCodeByIdsMulti")
    @WebMethod(action = "urn:queryMDMCodeByIdsMulti")
    @ResponseWrapper(localName = "queryMDMCodeByIdsMultiResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryMDMCodeByIdsMultiResponse")
    public java.util.List<com.yonyou.itf.mdm07.sharing.IDMapping> queryMDMCodeByIdsMulti(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "list", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.util.List<com.yonyou.itf.mdm07.sharing.SourceIDBean> list
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:deleteListMdByIds", output = "urn:deleteListMdByIdsResponse")
    @RequestWrapper(localName = "deleteListMdByIds", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.DeleteListMdByIds")
    @WebMethod(action = "urn:deleteListMdByIds")
    @ResponseWrapper(localName = "deleteListMdByIdsResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.DeleteListMdByIdsResponse")
    public com.yonyou.itf.mdm07.sharing.MdmRetVO deleteListMdByIds(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "list", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.util.List<java.lang.String> list
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:queryIdsMulti", output = "urn:queryIdsMultiResponse")
    @RequestWrapper(localName = "queryIdsMulti", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryIdsMulti")
    @WebMethod(action = "urn:queryIdsMulti")
    @ResponseWrapper(localName = "queryIdsMultiResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryIdsMultiResponse")
    public java.util.List<com.yonyou.itf.mdm07.sharing.IDMapping> queryIdsMulti(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "list", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.util.List<com.yonyou.itf.mdm07.sharing.SourceIDBean> list,
        @WebParam(name = "string2", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string2
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
    @Action(input = "urn:queryMdmcodeByGdCode", output = "urn:queryMdmcodeByGdCodeResponse")
    @RequestWrapper(localName = "queryMdmcodeByGdCode", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryMdmcodeByGdCode")
    @WebMethod(action = "urn:queryMdmcodeByGdCode")
    @ResponseWrapper(localName = "queryMdmcodeByGdCodeResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService", className = "com.yonyou.itf.mdm07.sharing.QueryMdmcodeByGdCodeResponse")
    public com.yonyou.itf.mdm07.sharing.MdmRetVO queryMdmcodeByGdCode(
        @WebParam(name = "string", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string1,
        @WebParam(name = "string2", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string2,
        @WebParam(name = "string3", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingCenterService")
        java.lang.String string3
    );
}
